services:
  - type: web
    name: sugria-backend
    env: node
    buildCommand: >
      yarn config set network-timeout 300000 &&
      yarn install --no-frozen-lockfile &&
      yarn global add @nestjs/cli &&
      npx prisma generate &&
      yarn build
    startCommand: yarn start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false 